
export const FETCH_ASSIGNMENT = "FETCH_ASSIGNMENT";

export const FETCH_ASSIGNMENT_SUCCEEDED = "FETCH_ASSIGNMENT_SUCCEEDED";

export const FETCH_ASSIGNMENT_FAILED = "FETCH_ASSIGNMENT_FAILED";

export const CREATE_ASSIGNMENT = "CREATE_ASSIGNMENT";

export const CREATE_ASSIGNMENT_SUCCESS = "CREATE_ASSIGNMENT_SUCCESS";

export const CREATE_ASSIGNMENT_FAILED = "CREATE_ASSIGNMENT_FAILED";


