
export const FETCH_ALL_ASSIGNMENT = "FETCH_ALL_ASSIGNMENT";

export const FETCH_ALL_ASSIGNMENT_SUCCEEDED = "FETCH_ALL_ASSIGNMENT_SUCCEEDED";

export const FETCH_ALL_ASSIGNMENT_FAILED = "FETCH_ALL_ASSIGNMENT_FAILED";

export const ASSIGNMENT_DASHBOARD_LOADED = "ASSIGNMENT_DASHBOARD_LOADED";

export const ASSIGNMENT_DASHBOARD_UNLOADED = "ASSIGNMENT_DASHBOARD_UNLOADED";

