
export const FETCH_DISCLOSURE = "FETCH_DISCLOSURE";

export const FETCH_DISCLOSURE_SUCCEEDED = "FETCH_DISCLOSURE_SUCCEEDED";

export const FETCH_DISCLOSURE_FAILED = "FETCH_DISCLOSURE_FAILED";

export const ADD_DISCLOSURE = "ADD_DISCLOSURE";

