export const FETCH_ALL_FIELDS_REQUEST = "FETCH_ALL_FIELDS_REQUEST";
export const FETCH_ALL_FIELDS_SUCCESS = "FETCH_ALL_FIELDS_SUCCESS";
export const FETCH_ALL_FIELDS_FAILURE = "FETCH_ALL_FIELDS_FAILURE";

// copy action
export const FETCH_COPY_REQUEST = "FETCH_COPY_REQUEST";
export const FETCH_COPY_SUCCESS = "FETCH_COPY_SUCCESS";
export const FETCH_COPY_FAILURE = "FETCH_COPY_FAILURE";
export const ADD_COPY_REQUEST = "ADD_COPY_REQUEST";
export const ADD_COPY_SUCCESS = "ADD_COPY_SUCCESS";
export const ADD_COPY_FAILURE = "ADD_COPY_FAILURE";
export const UPDATE_COPY_REQUEST = "UPDATE_COPY_REQUEST";

// backup action constant
export const FETCH_BACKUPS_REQUEST = "FETCH_BACKUPS_REQUEST";
export const FETCH_BACKUPS_SUCCESS = "FETCH_BACKUPS_SUCCESS";
export const FETCH_BACKUPS_FAILURE = "FETCH_BACKUPS_FAILURE";
export const ADD_BACKUPS_ITEM_REQUEST = "ADD_BACKUPS_ITEM_REQUEST";
export const ADD_BACKUPS_ITEM_SUCCESS = "ADD_BACKUPS_ITEM_SUCCESS";
export const ADD_BACKUPS_ITEM_FAILURE = "ADD_BACKUPS_ITEM_FAILURE";
export const UPDATE_BACKUPS_ITEM_REQUEST = "UPDATE_BACKUPS_ITEM_REQUEST";
export const UPDATE_BACKUPS_ITEM_SUCCESS = "UPDATE_BACKUPS_ITEM_SUCCESS";
export const UPDATE_BACKUPS_ITEM_FAILURE = "UPDATE_BACKUPS_ITEM_FAILURE";
export const DELETE_BACKUPS_ITEM_REQUEST = "DELETE_BACKUPS_ITEM_REQUEST";
export const DELETE_BACKUPS_ITEM_SUCCESS = "DELETE_BACKUPS_ITEM_SUCCESS";
export const DELETE_BACKUPS_ITEM_FAILURE = "DELETE_BACKUPS_ITEM_FAILURE";

// graphic
export const FETCH_GRAPHICS_REQUEST = "FETCH_GRAPHICS_REQUEST";
export const FETCH_GRAPHICS_SUCCESS = "FETCH_GRAPHICS_SUCCESS";
export const FETCH_GRAPHICS_FAILURE = "FETCH_GRAPHICS_FAILURE";
export const ADD_GRAPHICS_ITEM_REQUEST = "ADD_GRAPHICS_ITEM_REQUEST";
export const ADD_GRAPHICS_ITEM_SUCCESS = "ADD_GRAPHICS_ITEM_SUCCESS";
export const ADD_GRAPHICS_ITEM_FAILURE = "ADD_GRAPHICS_ITEM_FAILURE";
export const UPDATE_GRAPHICS_ITEM_REQUEST = "UPDATE_GRAPHICS_ITEM_REQUEST";
export const UPDATE_GRAPHICS_ITEM_SUCCESS = "UPDATE_GRAPHICS_ITEM_SUCCESS";
export const UPDATE_GRAPHICS_ITEM_FAILURE = "UPDATE_GRAPHICS_ITEM_FAILURE";
export const DELETE_GRAPHICS_ITEM_REQUEST = "DELETE_GRAPHICS_ITEM_REQUEST";
export const DELETE_GRAPHICS_ITEM_SUCCESS = "DELETE_GRAPHICS_ITEM_SUCCESS";
export const DELETE_GRAPHICS_ITEM_FAILURE = "DELETE_GRAPHICS_ITEM_FAILURE";

// upload file
export const FILE_UPLOAD_REQUEST = "FILE_UPLOAD_REQUEST";
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS";
//save form
export const UPLOAD_COPY_FORM_DATA = "UPLOAD_COPY_FORM_DATA";
export const UPLOAD_COPY_FORM_DATA_SUCCESS = "UPLOAD_COPY_FORM_DATA_SUCCESS";

//update user last login
export const USER_LAST_LOGIN = "USER_LAST_LOGIN";

// Update disclosureTags for saving into database
export const UPDATE_DISCLOSURE_TAGS_SUCCESS = "UPDATE_DISCLOSURE_TAGS_SUCCESS";

//create proof
export const CREATE_PROOF_REQUEST = "CREATE_PROOF_REQUEST";
export const CREATE_PROOF_SUCCESS = "CREATE_PROOF_SUCCESS";
export const CREATE_PROOF_FAILURE = "CREATE_PROOF_FAILURE";
export const CREATE_PROOF_VERSION_REQUEST = "CREATE_PROOF_VERSION_REQUEST";
export const CREATE_PROOF_VERSION_SUCCESS = "CREATE_PROOF_VERSION_SUCCESS";
export const CREATE_PROOF_VERSION_FAILURE = "CREATE_PROOF_VERSION_FAILURE";
export const PROOF_ACTION = "PROOF_ACTION";

//Twitter
export const TWITTER_MEDIA_REQUEST = "TWITTER_MEDIA_REQUEST";
export const TWITTER_MEDIA_UPDATE_REQUEST = "TWITTER_MEDIA_UPDATE_REQUEST";

//Linkedin
export const LINKEDIN_MEDIA_REQUEST = "LINKEDIN_MEDIA_REQUEST";
export const LINKEDIN_MEDIA_UPDATE_REQUEST = "LINKEDIN_MEDIA_UPDATE_REQUEST";

//Facebook
export const FACEBOOK_MEDIA_REQUEST = "FACEBOOK_MEDIA_REQUEST";
export const FACEBOOK_MEDIA_UPDATE_REQUEST = "FACEBOOK_MEDIA_UPDATE_REQUEST";

export const SOCIAL_DELETE_REQUEST = "SOCIAL_DELETE_REQUEST";
export const SOCIAL_DELETE_SUCCESS = "SOCIAL_DELETE_SUCCESS";

export const SAVE_ASSIGNMENT_SUCCEEDED = "SAVE_ASSIGNMENT_SUCCEEDED";

export const CLEAR_WRITE_STORE = "CLEAR_WRITE_STORE";
